# Generated by Django 3.1.3 on 2021-09-18 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodstuff',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rclass',
            field=models.CharField(choices=[('D', 'Drink'), ('E', 'Eat'), ('I', 'Ingredient')], default='D', max_length=1),
        ),
    ]
