---

- name: Create __init__.py for directory containing wsgi.py
  template: src=init_py.j2
    dest="{{ application_path }}/__init__.py"
    owner=graham
    group=graham
    mode="u=rw,g=rwx,o=r"

- name: Create the Apache configuration file
  template: src=httpd_conf.j2
    dest={{ application_path }}/apache2/conf/httpd.conf
    backup=yes
    owner=graham
    group=graham
    mode="u=rw,g=rwx,o=r"
  notify: restart apache

- name: Create the mod_wsgi file
  template: src=wsgi_py.j2
    dest={{ application_path }}/wsgi.py
    backup=yes
    owner=graham
    group=graham
    mode="u=rw,g=rwx,o=rw"
  notify: restart apache


- name: Ensure Apache service is started
  shell: ./restart
  args:
    chdir: "{{ application_path }}/apache2/bin"
    executable: /bin/bash

#  service: name=httpd
#    state=started
#    enabled=yes
