---

- name: Update an {{ application_name }} server

  hosts:
    - all

  vars_files:
    - env_vars/base.yml
    - env_vars/staging.yml

  roles:
    - web

  tasks:
    - shell: echo "almost done"

  post_tasks:
    notify:
    - restart apache